# Generated by Django 5.2.8 on 2025-11-26 09:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=10)),
                ('division', models.CharField(blank=True, max_length=1, null=True)),
                ('exam_type', models.CharField(choices=[('Unit Test 1', 'Unit Test 1'), ('Unit Test 2', 'Unit Test 2'), ('Mid Term', 'Mid Term'), ('Unit Test 3', 'Unit Test 3'), ('Final Exam', 'Final Exam')], max_length=50)),
                ('marks_obtained', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total_marks', models.FloatField(default=100)),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='marks', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='marks_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'marks',
                'unique_together': {('student', 'subject', 'exam_type', 'teacher')},
            },
        ),
    ]
