# Generated by Django 5.2.8 on 2025-12-03 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField(max_length=500)),
                ('subject', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=10)),
                ('division', models.CharField(blank=True, max_length=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='resources_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resources',
                'ordering': ['-created_at'],
            },
        ),
    ]
